package com.marcinsi;

import lombok.extern.slf4j.Slf4j;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@Slf4j
@SpringBootApplication
public class Main {

    // Field log is automatically generated by lombok

    public static void main(String[] args) {

        log.info("Guess The Number Game");

        // Starting an app in spring boot

        SpringApplication.run(Main.class, args);
    }
}
